server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_server
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "secret"
  expiration: 3600000