server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mercado_x
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        lob:
          non_contextual_creation: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9092
security:
  jwt:
    private-key-location: ${JWT_PRIVATE_KEY_LOCATION:file:./secrets/private.pem}
    public-key-location: ${JWT_PUBLIC_KEY_LOCATION:file:./secrets/public.pem}
    expiration: ${JWT_EXPIRATION:1h}
    key-id: ${JWT_KEY_ID:rsa-1}