server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mercado_x
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

security:
  jwt:
    secret: "secret"
    expiration: 3600000